function [ S ] = controlPanelGui()

btnString = 'Lidar OFF';

%Target point and orientation
targetX = 0;
targetY = 0;
%change target orientation here - in later version this will
%be implemented graphically
targetRot = 110;

%get information about current screen
Pix_SS = get(0,'screensize');

figW = 1300 ;
figH = 550 ;

screenH = Pix_SS(3);
screenW = Pix_SS(4);

xpos = ceil((screenH-figW)/2); 
ypos = ceil((screenW-figH)/2); 

%Prepare the plot window and constantly update with (drawnow)
S.myFigure = figure('Position', [xpos, ypos, figW, figH],'Resize','off',...
    'Color',[0.94 0.94 0.94]);

            
S.btnStart = uicontrol('Style','pushbutton','String','START','FontSize',12,...
         'Position',[20 20 90 30],'Callback', 'uiresume(gcbf)' ); 
     
uiwait(S.myFigure);
clf


%title label
S.titleLabel = uicontrol('Style','text','FontSize',20,...
                'Position',[10 520 250 30],...
                'String','Ship Control Panel','FontWeight','Bold');
            
%terminates the programm
S.btnExit = uicontrol('Style', 'pushbutton', 'String', 'Exit' ,'FontSize',12,...
                'ForegroundColor','Red','Position', [20 20 90 30]);
                %%'Callback', {@exitBtn,fid,myServer} );
            
S.serverButton = uicontrol('Style', 'pushbutton', 'String', 'Stop Server' ,'FontSize',12,...
                'Position', [120 20 100 30]);
                %%'Callback', {@serverConnect,myServer} ); 
                
%Lidar Panel ------------------ start           
S.lidarPanel = uipanel('Title','Lidar Panel','FontSize',12,...
     'Units','Pixels','Position',[220 160 350 350]);
%Rotation Window
subplot(1,2,1,'Parent',S.lidarPanel,'Units','Pixels','Position',[50 80 240 220])

%subplot(1,2,1)
%Set up polar scans for current and reference data
[Xref,Yref] = pol2cart((0:2*pi/360:2*pi*(1-1/360))',ones(360,1)+4000);
[theta,rho] = cart2pol(Xref,Yref);
S.polarRef = polar(theta,rho,'b.');
hold on
S.polarCur = polar((0:2*pi/360:2*pi*(1-1/360))',ones(360,1)+4000,'g.');
title('POLAR','FontWeight','Bold');

%Scans/sec label           
S.scanPerSecLabel = uicontrol('Parent',S.lidarPanel,'Style','text','FontSize',12,...
                'Position',[10 30 40 20],...
                'String','Freq');
%Scans/sec label           
S.freqIndicator = uicontrol('Parent',S.lidarPanel,'Style','text','FontSize',12,...
                'Position',[40 10 20 20],...
                'String','Hz');
%Scans/sec textbox           
S.scanPerSecTxt = uicontrol('Parent',S.lidarPanel,'Style','edit','FontSize',12,...
                'Position',[20 10 20 20],...
                'String','5','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive'); 


%turns lidar on/off
S.btnLidar = uicontrol('Parent',S.lidarPanel,'Style', 'pushbutton', 'String', btnString ,'FontSize',12,...
                'Position', [250 10 90 30]);
                %%'Callback', {@lidarBtn,fid,btnString} );
            
%Lidar Panel ------------------ end


%Scan matching results panel --------- start            
S.hsmPanel = uipanel('Title','HSM Results','FontSize',12,...
     'Units','Pixels','Position',[10 430 200 80]); 
 
            
%rotation label
S.rotationLabel = uicontrol('Parent',S.hsmPanel,'Style','text','FontSize',12,...
                'Position',[10 30 40 20],...
                'String','Rot' );
%rotation textbox        
S.rotationTxt = uicontrol('Parent',S.hsmPanel,'Style','edit','FontSize',12,...
                'Position',[10 10 40 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
%position X label            
S.positionLabel_X = uicontrol('Parent',S.hsmPanel,'Style','text','FontSize',12,...
                'Position',[65 30 50 20],...
                'String',' X ' );
%position X textbox                       
S.positionTxt_X = uicontrol('Parent',S.hsmPanel,'Style','edit','FontSize',12,...
                'Position',[65 10 50 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
%position Y label            
S.positionLabel_Y = uicontrol('Parent',S.hsmPanel,'Style','text','FontSize',12,...
                'Position',[130 30 50 20],...
                'String',' Y ' );
%position Y textbox                       
S.positionTxt_Y = uicontrol('Parent',S.hsmPanel,'Style','edit','FontSize',12,...
                'Position',[130 10 50 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');

%Scan matching results panel --------- end 

%Controller panel -------------------- start
S.controlPanel = uipanel('Title','Fuzzy Control Input','FontSize',12,...
     'Units','Pixels','Position',[10 200 200 220]); 
 
%distance label
S.distanceLabel = uicontrol('Parent',S.controlPanel,'Style','text','FontSize',12,...
                'Position',[10 170 70 20],...
                'String','Distance');
%distance textbox            
S.distanceTxt = uicontrol('Parent',S.controlPanel,'Style','edit','FontSize',12,...
                'Position',[10 150 70 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
%speed label
S.speedLabel = uicontrol('Parent',S.controlPanel,'Style','text','FontSize',12,...
                'Position',[10 125 70 20],...
                'String','Speed');
%speed textbox            
S.speedTxt = uicontrol('Parent',S.controlPanel,'Style','edit','FontSize',12,...
                'Position',[10 105 70 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
%main orientation difference label            
S.mainOrienLabel = uicontrol('Parent',S.controlPanel,'Style','text','FontSize',12,...
                'Position',[10 80 70 20],...
                'String','MainOrien' );
%main orientation difference textbox               
S.mainOrienTxt = uicontrol('Parent',S.controlPanel,'Style','edit','FontSize',12,...
                'Position',[10 60 70 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
%minor orientation difference label               
S.minorOrienLabel = uicontrol('Parent',S.controlPanel,'Style','text','FontSize',12,...
                'Position',[10 35 70 20],...
                'String','MinOrien' );
%minor orientation difference textbox               
S.minorOrienTxt = uicontrol('Parent',S.controlPanel,'Style','edit','FontSize',12,...
                'Position',[10 15 70 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive');
            
S.controlCheckBox = uicontrol('Parent',S.controlPanel,'Style','togglebutton','FontSize',12,...
                'Position',[90 10 100 30],...
                'String','AUTOPILOT ');
            
%success Led Label             
S.successLedLabel = uicontrol('Parent',S.controlPanel,'Style','text','FontSize',12,...
                'Position',[120 150 60 40],...
                'String','Success Led');
%success Led            
S.SuccessLed = uicontrol('Parent',S.controlPanel,'Style','pushbutton',...
   'Position',[143 135 15 15],...
   'Enable','on','BackgroundColor',[0.5 0.5 0.5]);

%Controller panel -------------------- end

                  
%set up the arrow showing current rotation           
[U,V] = pol2cart(deg2rad(0),3500 );
S.ha = gca;
S.hl = compass(S.ha,U,V);
delete(findall(S.hl,'type','line','linestyle',':'));
set(S.hl,'linewidth',2)   


S.mapPanel = uipanel('Title','Map','FontSize',12,...
     'Units','Pixels','Position',[790 70 500 440]);
 
%Rotation Window
subplot(1,2,2,'Parent',S.mapPanel,'Units','Pixels','Position',[55 40 400 360])

%Translation sub-Window
%subplot(1,2,2)
S.cartRef = plot(1,1,'g.');
hold on

%title('MAP','FontWeight','Bold'); 

%plot the line between current position and target position
S.linePlot = plot([1 targetX],[1 targetY],'b--','LineWidth',2);

%current rotation arrow
S.hRot = quiver(1,1,5*cos(deg2rad(0)),5*sin(deg2rad(0)),'Color','r','LineWidth',2);
%target rotation arrow
S.hTargetRot = quiver(1,1,5*cos(deg2rad(targetRot)),5*sin(deg2rad(targetRot)),'Color','g','LineWidth',2);
%current position and target point orientation arrow
S.hLineRot = quiver(1,1,5*cos(deg2rad(45)),5*sin(deg2rad(45)),'Color','m','LineWidth',2);
%current position marker
S.positionMarker = plot(1,1,'r.','MarkerSize',30.0);
%target position marker
S.targetMarker = plot(targetX,targetY,'bs','MarkerSize',15.0);

%Ship marker
S.ship = plot(0,0,'LineWidth',2);

%Target Position Panel ------------------ start
S.targetPanel = uipanel('Title','Target Position','FontSize',12,...
     'Units','Pixels','Position',[580 370 200 140]);
 
%position X label            
S.target_X_Label = uicontrol('Parent',S.targetPanel,'Style','text','FontSize',12,...
                'Position',[10 90 60 20],...
                'String','target X' );
%position X textbox                       
S.target_X_txt = uicontrol('Parent',S.targetPanel,'Style','edit','FontSize',12,...
                'Position',[10 70 60 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive'); 
            
%position Y label            
S.target_Y_Label = uicontrol('Parent',S.targetPanel,'Style','text','FontSize',12,...
                'Position',[80 90 60 20],...
                'String','target Y' );
%position Y textbox                       
S.target_Y_txt = uicontrol('Parent',S.targetPanel,'Style','edit','FontSize',12,...
                'Position',[80 70 60 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive'); 

%Rot textbox                       
S.target_Rot_txt = uicontrol('Parent',S.targetPanel,'Style','edit','FontSize',12,...
                'Position',[16 20 60 20],...
                'String','-','FontWeight','Bold',...
                'BackgroundColor','White','Enable','inactive'); 
            
%Rot label            
S.target_Rot_Label = uicontrol('Parent',S.targetPanel,'Style','text','FontSize',12,...
                'Position',[6 40 80 20],...
                'String','target Rot' ); 
            
%picks new target point
S.pickTargetRotbtn = uicontrol('Parent',S.targetPanel,'Style', 'pushbutton', 'String', 'Edit','FontSize',12,...
                'Position', [85 15 40 30] ); 
            
%picks new target point
S.pickTargetPointbtn = uicontrol('Parent',S.targetPanel,'Style', 'pushbutton', 'String', 'Pick','FontSize',12,...
                'Position', [150 65 40 30]);
            
%Target Position Panel ------------------ end

%Manual Control Panel ------------------- start
S.manualPanel = uipanel('Title','Manual Control','FontSize',12,...
     'Units','Pixels','Position',[580 70 200 300]);
 
%Propeller_Label           
S.Propeller_Label = uicontrol('Parent',S.manualPanel,'Style','text','FontSize',12,...
                'Position',[10 250 70 20],...
                'String','Propeller' );
%Propeller_txt                     
S.Propeller_txt = uicontrol('Parent',S.manualPanel,'Style','edit','FontSize',12,...
                'Position',[10 230 70 20],...
                'String','1500','FontWeight','Bold',...
                'BackgroundColor','White');
            
%Rudder_Label            
S.Rudder_Label = uicontrol('Parent',S.manualPanel,'Style','text','FontSize',12,...
                'Position',[10 200 70 20],...
                'String','Rudder' );
%Rudder_txt                       
S.Rudder_txt = uicontrol('Parent',S.manualPanel,'Style','edit','FontSize',12,...
                'Position',[10 180 70 20],...
                'String','1500','FontWeight','Bold',...
                'BackgroundColor','White');
            
%Bow_Label         
S.Bow_Label = uicontrol('Parent',S.manualPanel,'Style','text','FontSize',12,...
                'Position',[10 150 70 20],...
                'String','Bow Th' );
%Bow_Txt                      
S.Bow_Txt = uicontrol('Parent',S.manualPanel,'Style','edit','FontSize',12,...
                'Position',[10 130 70 20],...
                'String','1500','FontWeight','Bold',...
                'BackgroundColor','White');
%Rear_Label           
S.Rear_Label = uicontrol('Parent',S.manualPanel,'Style','text','FontSize',12,...
                'Position',[10 100 70 20],...
                'String','Rear Th' );
%Rear_Txt                     
S.Rear_Txt = uicontrol('Parent',S.manualPanel,'Style','edit','FontSize',12,...
                'Position',[10 80 70 20],...
                'String','1500','FontWeight','Bold',...
                'BackgroundColor','White');

%Stop Motor Values
S.stopMotorsBtn = uicontrol('Parent',S.manualPanel,'Style', 'pushbutton', 'String', 'Stop','FontSize',12,...
                'Position', [150 10 40 30]);
            
%Set Motors
S.setMotorsBtn = uicontrol('Parent',S.manualPanel,'Style', 'pushbutton', 'String', 'Set','FontSize',12,...
                'Position', [100 10 40 30]);
            
S.imuRotationTxt = uicontrol('Style','edit','FontSize',12,...
                   'Position',[400 100 40 20],...
                   'String','-','FontWeight','Bold',...
                   'BackgroundColor','White','Enable','inactive');            
%Manual Control Panel ------------------- end

end